print("CALCUADORA DE OPERAÇÕES:")
num1 = input("ESCOLHA UM NÚMERO: ")
num2 = input("ESCOLHA OUTRO NÚMERO: ")
soma = int(num1) + int(num2)
mult = int(num1) * int(num2)
subt = int(num1) - int(num2)
div = int(num1) / int(num2)
print("o resultado da soma é: " + str(soma))
print("o resultado da divisão é: " + str(div))
print("o resultado da multiplicação é: " + str(mult))
print("o resultado da subtração é: " + str(subt))